import { Contract, type ContractRunner, Interface } from "ethers";
import type { SocialPostsContract } from "../types";

export const SOCIAL_ABI = [
  "event ProfileUpdated(address indexed account, string name, string bio, string avatar)",
  "event ProfileModerated(address indexed admin, address indexed account, string name, string bio, string avatar)",
  "event ProfileClearedByAdmin(address indexed admin, address indexed account)",
  "event PostMinted(address indexed author, uint256 indexed tokenId, string title, string body, string tokenURI)",
  "event PosterAllowed(address indexed account, bool allowed)",
  "event ModeratorSet(address indexed admin, address indexed account, bool enabled)",
  "event PosterApprovalRequested(address indexed account)",
  "event PostLiked(address indexed liker, uint256 indexed tokenId)",
  "event PostUnliked(address indexed unliker, uint256 indexed tokenId)",
  "event PostCommented(address indexed commenter, uint256 indexed tokenId, string comment)",
  "event CommentAdded(address indexed commenter, uint256 indexed tokenId, uint256 indexed commentId, uint256 parentId, string comment)",
  "event CommentEdited(address indexed editor, uint256 indexed tokenId, uint256 indexed commentId, string comment)",
  "event CommentDeleted(address indexed deleter, uint256 indexed tokenId, uint256 indexed commentId)",
  "event CommentLiked(address indexed liker, uint256 indexed tokenId, uint256 indexed commentId)",
  "event CommentUnliked(address indexed unliker, uint256 indexed tokenId, uint256 indexed commentId)",
  "event CommentSaved(address indexed saver, uint256 indexed tokenId, uint256 indexed commentId)",
  "event CommentUnsaved(address indexed unsaver, uint256 indexed tokenId, uint256 indexed commentId)",
  "event CommentTipped(address indexed tipper, address indexed author, uint256 indexed tokenId, uint256 commentId, uint256 amountWei)",
  "event PostReported(address indexed reporter, uint256 indexed tokenId, string reason)",
  "event CommentReported(address indexed reporter, uint256 indexed tokenId, uint256 indexed commentId, string reason)",
  "event PostSaved(address indexed saver, uint256 indexed tokenId)",
  "event PostUnsaved(address indexed unsaver, uint256 indexed tokenId)",
  "event Followed(address indexed follower, address indexed followee)",
  "event Unfollowed(address indexed follower, address indexed followee)",
  "event PostTipped(address indexed tipper, address indexed author, uint256 indexed tokenId, uint256 amountWei)",
  "event TipsWithdrawn(address indexed author, uint256 amountWei)",
  "event PostUpdated(address indexed author, uint256 indexed tokenId, string title, string body, string tokenURI)",
  "event PostEditedStatus(address indexed author, uint256 indexed tokenId, bool edited)",
  "event PostUpdatedByAdmin(address indexed admin, address indexed author, uint256 indexed tokenId, string title, string body, string tokenURI)",
  "event PostBurned(address indexed author, uint256 indexed tokenId)",
  "event PostBurnedByAdmin(address indexed admin, address indexed author, uint256 indexed tokenId)",
  "event PostFrozen(address indexed author, uint256 indexed tokenId)",

  "function MAX_NAME_LENGTH() external view returns (uint256)",
  "function MAX_BIO_LENGTH() external view returns (uint256)",
  "function MAX_AVATAR_LENGTH() external view returns (uint256)",
  "function MAX_COMMENT_LENGTH() external view returns (uint256)",
  "function MAX_POST_TITLE_LENGTH() external view returns (uint256)",
  "function MAX_POST_BODY_LENGTH() external view returns (uint256)",
  "function MAX_REPORT_LENGTH() external view returns (uint256)",

  "function setProfile(string name, string bio, string avatar) external",
  "function adminSetProfile(address account, string name, string bio, string avatar) external",
  "function adminClearProfile(address account) external",
  "function adminResetAccount(address account, uint256[] tokenIds) external",
  "function profileOf(address account) external view returns (string name, string bio, string avatar)",
  "function owner() external view returns (address)",
  "function setPosterAllowed(address account, bool allowed) external",
  "function setModerator(address account, bool enabled) external",
  "function isModerator(address account) external view returns (bool)",
  "function isPosterAllowed(address account) external view returns (bool)",
  "function hasPosterRequested(address account) external view returns (bool)",
  "function wasPosterDisapproved(address account) external view returns (bool)",

  // Ownable
  "function owner() external view returns (address)",
  "function requestPosterApproval() external",
  "function mintPost(string tokenUri, string title, string body) external returns (uint256 tokenId)",
  "function likePost(uint256 tokenId) external",
  "function unlikePost(uint256 tokenId) external",
  "function commentPost(uint256 tokenId, string comment) external",
  "function replyToComment(uint256 tokenId, uint256 parentCommentId, string comment) external",
  "function editComment(uint256 tokenId, uint256 commentId, string comment) external",
  "function deleteComment(uint256 tokenId, uint256 commentId) external",
  "function likeComment(uint256 tokenId, uint256 commentId) external",
  "function unlikeComment(uint256 tokenId, uint256 commentId) external",
  "function saveComment(uint256 tokenId, uint256 commentId) external",
  "function unsaveComment(uint256 tokenId, uint256 commentId) external",
  "function tipComment(uint256 tokenId, uint256 commentId) external payable",
  "function reportPost(uint256 tokenId, string reason) external",
  "function reportComment(uint256 tokenId, uint256 commentId, string reason) external",
  "function savePost(uint256 tokenId) external",
  "function unsavePost(uint256 tokenId) external",

  "function follow(address followee) external",
  "function unfollow(address followee) external",
  "function isFollowing(address follower, address followee) external view returns (bool)",

  "function freezePost(uint256 tokenId) external",
  "function isPostFrozen(uint256 tokenId) external view returns (bool)",
  "function isPostEdited(uint256 tokenId) external view returns (bool)",

  "function tipPost(uint256 tokenId) external payable",
  "function withdrawTips() external",
  "function updatePostURI(uint256 tokenId, string tokenUri, string title, string body) external",
  "function adminUpdatePostURI(uint256 tokenId, string tokenUri, string title, string body) external",
  "function burnPost(uint256 tokenId) external",
  "function adminBurnPost(uint256 tokenId) external",
  "function likesOf(uint256 tokenId) external view returns (uint256)",
  "function commentsOf(uint256 tokenId) external view returns (uint256)",
  "function savesOf(uint256 tokenId) external view returns (uint256)",
  "function tipsOf(uint256 tokenId) external view returns (uint256)",
  "function commentInfo(uint256 commentId) external view returns (address author, uint256 tokenId, uint256 parentId, bool deleted, bool edited, uint256 likeCount, uint256 saveCount, uint256 tipWei)",
  "function commentLikesOf(uint256 tokenId, uint256 commentId) external view returns (uint256)",
  "function commentSavesOf(uint256 tokenId, uint256 commentId) external view returns (uint256)",
  "function commentTipsOf(uint256 tokenId, uint256 commentId) external view returns (uint256)",
  "function withdrawableOf(address account) external view returns (uint256)",
  "function authorOf(uint256 tokenId) external view returns (address)",
  "function exists(uint256 tokenId) external view returns (bool)",
  "function hasLiked(uint256 tokenId, address account) external view returns (bool)",
  "function hasSaved(uint256 tokenId, address account) external view returns (bool)",
  "function hasLikedComment(uint256 tokenId, uint256 commentId, address account) external view returns (bool)",
  "function hasSavedComment(uint256 tokenId, uint256 commentId, address account) external view returns (bool)",
  "function tokenURI(uint256 tokenId) external view returns (string)"
] as const;

export const socialInterface = new Interface(SOCIAL_ABI);

export function getSocialContract(address: string, runner: ContractRunner): SocialPostsContract {
  return new Contract(address, SOCIAL_ABI, runner);
}
